name: release-pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Build the sdist and the wheel
      run: |
        pip install build
        python3 -m build
    - name: Check the sdist installs and imports
      run: |
          mkdir -p test-sdist
          cd test-sdist
          python -m venv venv-sdist
          venv-sdist/bin/python -m pip install numpy
          venv-sdist/bin/python -m pip install ../dist/tsdisagg*.tar.gz
          echo "Checking import and version number (on release)"
          venv-sdist/bin/python -c "import tsdisagg as ts; assert ts.__version__ == '${{ github.ref_name }}'[1:] if '${{ github.ref_type }}' == 'tag' else True; print(ts.__version__)"
          cd ..
    - name: Check the bdist installs and imports
      run: |
            mkdir -p test-bdist
            cd test-bdist
            python -m venv venv-bdist
            venv-bdist/bin/python -m pip install ../dist/tsdisagg*.whl
            echo "Checking import and version number (on release)"
            venv-bdist/bin/python -c "import tsdisagg as ts; assert ts.__version__ == '${{ github.ref_name }}'[1:] if '${{ github.ref_type }}' == 'tag' else ts.__version__; print(ts.__version__)"
            cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: dist/*

  publish:
    name: upload release to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1

  check-published:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Give PyPI a chance to update the index
      run: sleep 360
    - name: Install from PyPI
      run: |
        pip install tsdisagg==${GITHUB_REF:11}
